/* Activity pane + UI beacon (static/activity.js), against the REAL index.html.
 *
 * Same approach as test_ui_chat_modes.js: parse the page with jsdom, evaluate
 * app.js + chat.js + activity.js + the checks as ONE script so the top-level
 * `let`/`const` bindings are shared the way a browser shares them.
 * The report payloads are a fixture generated by activity.report() itself
 * (tests/fixtures/activity_report.json), so the UI is tested against the
 * server's real shape, not a hand-typed guess at it.
 *
 *     npm install jsdom && node tests/test_ui_activity.js
 */
const fs = require("fs");
const path = require("path");

let JSDOM;
try {
  ({ JSDOM } = require("jsdom"));
} catch (e) {
  try {
    ({ JSDOM } = require(path.join("/tmp", "node_modules", "jsdom")));
  } catch (e2) {
    console.log("SKIP: jsdom is not installed (npm install jsdom to run these checks).");
    process.exit(0);
  }
}

const STATIC = path.join(__dirname, "..", "static");
const read = f => fs.readFileSync(path.join(STATIC, f), "utf8");
const FIXTURE = JSON.parse(fs.readFileSync(path.join(__dirname, "fixtures", "activity_report.json"), "utf8"));

const dom = new JSDOM(read("index.html"), { runScripts: "outside-only", url: "http://localhost/" });
const { window } = dom;

const posted = [];
const requested = [];
window.fetch = async (url, opts = {}) => {
  url = String(url);
  requested.push(url);
  let json = {};
  if (url.startsWith("/api/activity/events")) { posted.push(JSON.parse(opts.body)); json = { accepted: 1 }; }
  else if (url.startsWith("/api/activity/me")) json = FIXTURE.me;
  else if (url.startsWith("/api/admin/activity")) json = FIXTURE.admin;
  else if (url.startsWith("/api/admin/users")) json = { dana: {}, sam: {}, priya: {} };
  else if (url.startsWith("/api/usage/me")) json = { totals: {}, by_day: [], quota: { unlimited: true } };
  else if (url.startsWith("/api/auth/me")) return { ok: false, status: 401, json: async () => ({}) };
  return { ok: true, status: 200, json: async () => json, text: async () => JSON.stringify(json) };
};
window.navigator.sendBeacon = (u, blob) => { posted.push({ beacon: true }); return true; };

const failures = [];
window.__check = (label, cond, extra) => {
  console.log(`  [${cond ? "PASS" : "FAIL"}] ${label}` + (!cond && extra ? `  ${extra}` : ""));
  if (!cond) failures.push(label);
};
window.__log = msg => console.log(msg);
window.__posted = posted;
window.__requested = requested;
window.__FIXTURE = FIXTURE;

const CHECKS = `
const check = window.__check, log = window.__log;
const $ = id => document.getElementById(id);
const tick = (ms = 0) => new Promise(r => setTimeout(r, ms));
const FIXTURE = window.__FIXTURE;

(async () => {
  log("\\n-- page structure --");
  check("usage switch exists with two panes", !!$("usageSwitch") && !!$("usagePaneActivity") && !!$("usagePaneTokens"));
  check("token pane starts hidden, activity pane visible", $("usagePaneTokens").hidden && !$("usagePaneActivity").hidden);
  for (const id of ["myActivityKpis","myActivityChannels","myActivityFeatures","myActivityRecent","actKpis","actTrend",
                    "actSegments","actLadder","actChannels","actFeatures","actTools","actClients","actLogParser",
                    "actUsers","actAccounts","actOrgs","actHours","actErrors","actRecent","actDays","actUser"]) {
    if (!$(id)) check("element #" + id + " exists", false);
  }
  check("every element the renderer writes to exists", true);

  log("\\n-- a writer sees only their own activity --");
  CURRENT_USER = { username: "dana", role: "user" };
  applyRole();
  installActivityHooks();
  await loadActivityView();
  await tick(5);
  check("own KPIs render", $("myActivityKpis").innerHTML.includes("Logs parsed"));
  check("own channel split renders", $("myActivityChannels").innerHTML.includes("ch-stack"));
  check("own segment is named", $("myActivityChannels").innerHTML.includes(FIXTURE.me.me.segment));
  check("own features table filled", $("myActivityFeatures").querySelectorAll("tr").length > 0);
  check("the admin endpoint was never called by a writer",
    !window.__requested.some(u => u.startsWith("/api/admin/activity")));

  log("\\n-- an admin sees everyone --");
  CURRENT_USER = { username: "admin", role: "admin" };
  applyRole();
  await loadActivityView();
  await tick(5);
  const a = FIXTURE.admin;
  check("KPIs include the no-AI-spend users", $("actKpis").innerHTML.includes("Users with no AI spend")
        && $("actKpis").innerHTML.includes(">" + a.totals.non_llm_users + "<"));
  check("daily trend has one bar per day", ($("actTrend").innerHTML.match(/usage-bar-wrap/g) || []).length === a.by_day.length);
  check("trend is stacked by channel", $("actTrend").innerHTML.includes("ch-bg-mcp-remote"));
  check("segments list MCP-only users", $("actSegments").innerHTML.includes("MCP only (no in-app LLM)"));
  check("ladder has every step", ($("actLadder").innerHTML.match(/ladder-row/g) || []).length === a.ladder.length);
  check("channel table rows", $("actChannels").querySelectorAll("tr").length === a.by_channel.length);
  check("tools table lists find_field_writers", $("actTools").innerHTML.includes("find_field_writers"));
  check("clients table lists claude-ai", $("actClients").innerHTML.includes("claude-ai"));
  check("log parser card shows volume", $("actLogParser").innerHTML.includes("MB"));
  check("user table has one row per user", $("actUsers").querySelectorAll("tr").length === a.by_user.length);
  check("account rollup shows Acme Corp", $("actAccounts").innerHTML.includes("Acme Corp"));
  check("24 hour buckets", ($("actHours").innerHTML.match(/usage-bar-wrap/g) || []).length === 24);
  check("recent feed renders", $("actRecent").querySelectorAll(".act-row").length > 0);

  log("\\n-- drilldown --");
  const row = $("actUsers").querySelector("tr");
  row.click();
  await tick(5);
  check("clicking a user narrows the page to them",
    $("actUser").value !== "" && window.__requested.some(u => u.includes("/api/admin/activity?") && u.includes("username=")));

  log("\\n-- pane switching --");
  showUsagePane("tokens");
  check("tokens pane shows", !$("usagePaneTokens").hidden && $("usagePaneActivity").hidden);
  showUsagePane("activity");
  check("and back", $("usagePaneTokens").hidden && !$("usagePaneActivity").hidden);

  log("\\n-- beacon --");
  window.__posted.length = 0;
  showView("logs");
  showView("known");
  trackUi("ui.copy", { target: "rca-json" });
  flushUiEvents();
  await tick(5);
  const batch = window.__posted.find(p => p.events);
  check("tab switches are batched into one post", !!batch && batch.events.length >= 3,
    JSON.stringify(window.__posted).slice(0, 200));
  check("...as ui.view with the tab name", batch && batch.events.some(e => e.action === "ui.view" && e.meta.view === "logs"));
  check("showView still does its job after being hooked", $("view-known").classList.contains("active"));
  check("hooks are not installed twice", (() => { installActivityHooks(); return showView.__actHooked === true; })());
  CURRENT_USER = null;
  trackUi("ui.view", { view: "x" });
  check("nothing is queued without a signed-in user", ACT_QUEUE.length === 0);

  window.__done();
})().catch(e => { check("no exception", false, e && e.stack); window.__done(); });
`;

window.__done = () => {
  console.log();
  if (failures.length) {
    console.log(`${failures.length} FAILURE(S):`);
    failures.forEach(f => console.log("  - " + f));
    process.exit(1);
  }
  console.log("All activity UI checks passed.");
  process.exit(0);
};

window.eval(read("app.js") + "\n;\n" + read("chat.js") + "\n;\n" + read("activity.js") + "\n;\n" + CHECKS);
